sfdx-source/main/objects/Org_Configuration__mdt/Org_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Generic key-value configuration</description>
    <label>Org Configuration</label>
    <pluralLabel>Org Configurations</pluralLabel>
</CustomObject>

sfdx-source/main/objects/Org_Configuration__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Primitive data type of the value</description>
    <inlineHelpText>Primitive data type of the value</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>List&lt;String&gt;</fullName>
            </value>
            <value>
                <fullName>Set&lt;String&gt;</fullName>
            </value>
            <value>
                <fullName>Map&lt;String,String&gt;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/objects/Org_Configuration__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value associated to this key</description>
    <inlineHelpText>Value associated to this key</inlineHelpText>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/main/classes/OrgConfigurationSelector.cls
/**
 * Selector class for Org_Configuration__mdt
 */
public without sharing class OrgConfigurationSelector {
    
    /**
     * Retrieves the Org Configuration record for a given configuration name (if active)
     * @param configName developer name of the configuration record we want to get
     * @return the corresponding record for that name or null if not found
     */
    public Org_Configuration__mdt getOrgConfiguration(String configName) {
        // No issue with doing queries individually since they do not count for SOQL limit
        List<Org_Configuration__mdt> configuration = [SELECT Value__c, Type__c FROM Org_Configuration__mdt
                                                      WHERE DeveloperName = :configName AND Active__c = true];
        return !configuration.isEmpty() ? configuration.get(0) : null;
    }
}